services:
  redis-database:
    container_name: redis-database
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - redis-data:/data
    
  postgres-database:
    container_name: postgres-database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lateralus_db
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  redis-data:
  postgres-data: